# Generated by Django 5.2.15 on 2026-06-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_Logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learning_Logs.topic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
